ordercloud-api/angular-components

src/app/app.js
src/app/base/templates/base.top.tpl.html
src/app/common/impersonation/ordercloud-impersonation.js
src/app/login/login.js

adding the ability to stop impersonation if it is occurring on the account drop-down.

Impersonation Changes

---

src/app/base/base.js
src/app/base/less/base.less
src/app/base/templates/base.left.tpl.html
src/app/base/tests/base.spec.js
src/app/catalog/catalog.js
src/app/catalog/templates/catalog.tpl.html

Category tree

---

catalog/catalog.js
catalog/product/less/product.less
catalog/product/product.js
catalog/product/templates/addToOrder.tpl.html
catalog/product/templates/product.tpl.html
catalog/product/templates/specform.tpl.html

OC-421 Create directives for Specs and Add to Order

Adding oc-spec-form and oc-add-to-order directives

---

checkout/checkout.js

OC-441 Add toaster upon unsuccessful submit of order

OC-440 Add toaster upon successful submit of order

---

orderHistory/orderHistory.js
orderHistory/templates/repeatOrder.tpl.html
repeatOrder/repeatOrder.js
repeatOrder/repeatOrder.md
repeatOrder/templates/repeatOrder.html

OC-376 repeat order for Justin King

Refactor repeatOrder to work with admin perspective

---

priceSchedules/priceBreakService.js
priceSchedules/priceSchedules.js
priceSchedules/templates/priceScheduleCreate.tpl.html
priceSchedules/templates/priceScheduleEdit.tpl.html

@mirandaposthumus  went through and cleared out spacing

Price schedule bug

---

catalog/product/ordercloud-order-input.js
creditCards/creditCards.js
creditCards/templates/creditCardCreate.tpl.html
creditCards/templates/creditCardEdit.tpl.html

@mirandaposthumus  clean up bug fix 42

Bugfix #42 clear console logs and unnecessary line breaks

---

userGroups/templates/userGroupCreate.tpl.html
userGroups/templates/userGroupEdit.tpl.html

@mirandaposthumus  updated input model

updated model for input to IsReportingGroup

---

adminUsers/adminUsers.js
coupons/coupons.js
priceSchedules/priceSchedules.js
products/products.js
specs/specs.js

Removed "Edited" Replaced with "Updated" on toastr success calls

---

giftCards/templates/giftCardEdit.tpl.html
spendingAccounts/templates/spendingAccountCreate.tpl.html

Add step= "any " and min = 0 to input form in GiftCard Edit and Spending Account Create

---

addresses/templates/addressCreate.tpl.html
addresses/templates/addressEdit.tpl.html
adminUsers/templates/adminUserCreate.tpl.html
adminUsers/templates/adminUserEdit.tpl.html
buyers/templates/buyerCreate.tpl.html
buyers/templates/buyerEdit.tpl.html
categories/templates/categoryCreate.tpl.html
categories/templates/categoryEdit.tpl.html
costCenters/templates/costCenterCreate.tpl.html
costCenters/templates/costCenterEdit.tpl.html
giftCards/templates/giftCardCreate.tpl.html
giftCards/templates/giftCardEdit.tpl.html
priceSchedules/templates/priceScheduleCreate.tpl.html
priceSchedules/templates/priceScheduleEdit.tpl.html
products/templates/productCreate.tpl.html
products/templates/productEdit.tpl.html
shipments/templates/shipmentEdit.tpl.html
specs/templates/specCreate.tpl.html
specs/templates/specEdit.tpl.html
spendingAccounts/templates/spendingAccountCreate.tpl.html
spendingAccounts/templates/spendingAccountEdit.tpl.html
userGroups/templates/userGroupCreate.tpl.html
userGroups/templates/userGroupEdit.tpl.html
users/templates/userCreate.tpl.html
users/templates/userEdit.tpl.html

Remove regex from name input - to allow for spaces in names input

---

spendingAccounts/spendingAccounts.js
spendingAccounts/templates/spendingAccounts.tpl.html

Please approve change to seed as well

Spending account bug fix

---

checkout/payment/checkout.payment.js
checkout/payment/templates/payment.tpl.html
checkout/templates/confirmation.tpl.html
checkout/templates/review.tpl.html
expressCheckout/expressCheckout.js
expressCheckout/templates/expressCheckout.tpl.html
expressCheckout/templates/expressCheckoutReview.tpl.html

@mirandaposthumus  there are no errors when using express checkout

Make po entry

---

orders/orders.js

OC-588 Allow the user to save the line item if the order quantity falls between the product restricted min and max

OrderEdit: Save Line Item 

---

orders/templates/orderEdit.tpl.html

editing trash button for orderEdit.tpl.html

OC-399 edit trash button in orderEdit.tpl.html

---

checkout/payment/checkout.payment.js
checkout/payment/templates/payment.tpl.html

OC-509 update Credit Card Expiration date picker
OC-528 fix error associate with  date picker by updateing Credit Card Date Picker
@mirandaposthumus

Update Checkout Credit Card Date Picker

---

users/templates/userCreate.tpl.html
users/templates/userEdit.tpl.html
users/users.js

OC-224
After a user is added and assigned to a group, make sure that a Retail Buyer can log-in with the created credentials.
Create security profile dropdown list in UserCreate and UserEdit
Updates user.SecurityProfileID
@mirandaposthumus

Security Profiles for Users

---

adminUsers/adminUsers.js
adminUsers/templates/adminUserCreate.tpl.html
adminUsers/templates/adminUserEdit.tpl.html

OC-223
Add Security Profile resolve to Create Admin and  edit  Admin
Add Security Profile Select field to Create Admin and Edit Admin
@mirandaposthumus  sorry the branch name could have been more descriptive.

Security Profiles for Admin

---

checkout/payment/checkout.payment.js
checkout/payment/templates/payment.tpl.html
coupons/templates/couponCreate.tpl.html
coupons/templates/couponEdit.tpl.html
giftCards/templates/giftCardCreate.tpl.html
giftCards/templates/giftCardEdit.tpl.html
shipments/templates/shipmentCreate.tpl.html
shipments/templates/shipmentEdit.tpl.html

"now there ain't" - Kyle Olson

Mobile date pickers

---

catalog/productQuickView/productQuickView.js
catalog/productQuickView/templates/catalogSearch.quickviewModal.tpl.html

Small design improvements and a small spec options fix.

OC-423 Refactor catalog/product and specs/add to order directives

---

cart/cart.js
cart/test/cart.spec.js

Cart unit test

---

cart/cart.js
cart/templates/cart.tpl.html

Cart and checkout update quantities

---

cart/less/minicart.less
cart/templates/minicart.tpl.html
categories/categories.js
categories/less/categories.less
categories/templates/categoryTree.tpl.html
orders/less/orders.less

These are some adjustments for the components that appear in the Base template.
Also a quick fix for collapsing nodes on the category tree... it was annoying me.

Implementing Angular Snap

---

creditCards/creditCards.js

OC-790 fixed credit card logic to include the last day of the month 

---

priceSchedules/priceBreakService.js

OC-546 Throw error when max quantity is reached when entering price breaks into the Price Schedule

---

shipments/shipments.js

OC-845 Line Items Can now be saved to shipments

---

costCenters/costCenters.js
costCenters/templates/costCenters.filters.tpl.html
costCenters/templates/costCenters.list.tpl.html
costCenters/templates/costCenters.tpl.html
orderHistory/orderHistory.js
orderHistory/templates/orderHistory.list.tpl.html

this is adding the new list view pagination to the cost centers component. It should look like cards on mobile, the pagination on desktop should disappear when there's only one page available.

Components List View: Cost centers list OC-618

---

users/templates/users.filters.tpl.html
users/templates/users.list.tpl.html
users/templates/users.tpl.html
users/users.js

-add more columns of data
-sort them
-search on them
-pagination
@robertsoniv

OC-914 update the display list for the user's components

---

creditCards/creditCards.js
specs/specs.js
specs/templates/specs.filters.tpl.html
specs/templates/specs.list.tpl.html
specs/templates/specs.tpl.html

Oc 922 component list view specs zd

---

addresses/addresses.js
addresses/templates/addressCreate.tpl.html
addresses/templates/addressEdit.tpl.html

Components - State Dropdown should be text only when the country selected isn't USA or Canada.

OC-844 state dropdown bug

---

products/products.js

OC-957, PriceSchedule.list was missing an argument.

---

categories/categories.js

@robertsoniv let me know if there is a better solution.

OC-958 Added all to the depth arguement in the Categories.list call

---

catalog/category/category.js
catalog/category/tests/category.spec.js

OC-1304 fixing catalog me.listSubCategories no longer exists - AMR

OC-1304 fixing catalog me.listSubCategories no longer exists - AMR

---

adminUsers/adminUsers.js
adminUsers/templates/adminUserCreate.tpl.html
adminUsers/templates/adminUserEdit.tpl.html
cart/test/cart.spec.js
securityProfiles/less/securityProfiles.less
securityProfiles/securityProfiles.js
securityProfiles/templates/SecurityProfileRoles.tpl.html
securityProfiles/templates/securityProfileAccordion.tpl.html
securityProfiles/templates/securityProfileAssignments.tpl.html
securityProfiles/templates/securityProfileCreateAssignment.tpl.html
securityProfiles/templates/securityProfiles.tpl.html
securityProfiles/test/securityProfiles.spec.js
users/templates/userCreate.tpl.html
users/templates/userEdit.tpl.html
users/tests/users.spec.js
users/users.js

I made changes/pull request to the seed as well, specifically to extend the capabilities of the ordercloud-search directive which I used for this component.

Security profiles component 1158 cr

---

products/products.js
products/templates/productCreateAssignment.tpl.html

Product Assignments takes PriceScheduleID instead of  ReplenishmentPriceScheduleID and StandardPriceScheduleID.
We'll probably want to wait until the SDK is updated with these changes before we merge this in

OC-1407 refactor for product assignments for breaking change

---

specs/specs.js
specs/templates/specEdit.tpl.html

spec options are their own object, no longer a part of the spec object

OC-1735 update specs component to work with breaking changes

---

myOrders/myOrders.js

Bug fix for saving an increase/decrease in line item quantity for a product in My Orders Component.

Bug fix for saving line item quantity in My Orders Component

---

checkout/checkout.js

@olsonkr 
set vm.currentOrder.ShippingAddressId to null everytime the controller loads
https://four51.atlassian.net/browse/OC-742

default shipping address blank

---

checkout/billing/checkout.billing.js

@olsonkr 
small change. I was getting the error because I had CORS enabled

update response parameter

---

catalog/product/templates/addToOrder.tpl.html

@olsonkr 
fixed form validation to read min and max quantities before enabling add to cart button

OC-729 fixed form validation to check min and max before validated
